name: Release Extension

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP archive
        run: |
          zip -r extension.zip . -x "*.git*" ".github/*" ".gitignore" "README.md" "docs/*" "node_modules/*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: extension.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
